### ISSUE TITLE
试了一下，chatglm6B，报了新的错误

### ISSUE THREAD

**Issue by LebronXierunfeng** [GIOGIOv587/NBCEonChatGLM6b#1]
Traceback (most recent call last):
  File "/home/xierunfeng/NBCE-main/test.py", line 111, in <module>
    generate(1000)
  File "/home/xierunfeng/miniconda3/envs/test/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/xierunfeng/NBCE-main/test.py", line 67, in generate
    _attention_mask = get_attention_mask(attention_mask)
  File "/home/xierunfeng/NBCE-main/test.py", line 45, in get_attention_mask
    if attention_mask[i][j] == 0:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

**Comment by GioGioBond** [comment]
> 

我研究一下

**Comment by GUORUIWANG** [comment]
我试了一下也是这个错误

**Comment by GioGioBond** [comment]
@GUORUIWANG @LebronXierunfeng 可以试一下新上传的test.py，如果有任何问题，可以随意留言，我会修改

**Comment by LebronXierunfeng** [comment]
> @GUORUIWANG @LebronXierunfeng 可以试一下新上传的test.py，如果有任何问题，可以随意留言，我会修改

没有解决，依旧是这个RuntimeError: Boolean value of Tensor with more than one value is ambiguous

**Comment by GioGioBond** [comment]
@LebronXierunfeng  第96行屏蔽一下，我测试用的，忘记屏蔽了

**Comment by LebronXierunfeng** [comment]
> 



> @LebronXierunfeng 第96行屏蔽一下，我测试用的，忘记屏蔽了

报错解决了，但是输出不太正常，全都是['<0xE8>']

**Comment by GioGioBond** [comment]
> > 
> 
> > @LebronXierunfeng 第96行屏蔽一下，我测试用的，忘记屏蔽了
> 
> 报错解决了，但是输出不太正常，全都是['<0xE8>']

114行改为 attention_mask=_attention_mask

**Comment by LebronXierunfeng** [comment]
> > > 
> > 
> > 
> > > @LebronXierunfeng 第96行屏蔽一下，我测试用的，忘记屏蔽了
> > 
> > 
> > 报错解决了，但是输出不太正常，全都是['<0xE8>']
> 
> 114行改为 attention_mask=_attention_mask

改完之后报了解码错误，UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 7: ordinal not in range(128)，然后我把open那边文件编码改成utf-8之后，输出变成了[ ' < n > ' ]

**Comment by GioGioBond** [comment]
> > > > 
> > > 
> > > 
> > > > @LebronXierunfeng 第96行屏蔽一下，我测试用的，忘记屏蔽了
> > > 
> > > 
> > > 报错解决了，但是输出不太正常，全都是['<0xE8>']
> > 
> > 
> > 114行改为 attention_mask=_attention_mask
> 
> 改完之后报了解码错误，UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 7: ordinal not in range(128)，然后我把open那边文件编码改成utf-8之后，输出变成了[ ' < n > ' ]

加我Q 842862509

**Comment by GUORUIWANG** [comment]
最终解决了吗大佬

**Comment by GioGioBond** [comment]
> 最终解决了吗大佬

下载最新版本chatglm，已经解决
