### ISSUE TITLE
用更新过的代码试了下，还是有bug

### ISSUE THREAD

**Issue by TianWuYuJiangHenShou** [GIOGIOv587/NBCEonChatGLM6b#2]
vocab_size:150528  这个版本的chatglm,出现了这个bug
```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File
"/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py",
line 198, in <fused code>
    cos, sin = F.embedding(position_id, cos.squeeze(1)).unsqueeze(2), \
        F.embedding(position_id, sin.squeeze(1)).unsqueeze(2)
    q, k = (q * cos) + (rotate_half(q) * sin), (k * cos) + (rotate_half(k) * sin)
            ~~~~~~~ <--- HERE
    return q, k
RuntimeError: The size of tensor a (103) must match the size of tensor b (102) at
non-singleton dimension 0
```

**Comment by GioGioBond** [comment]
> vocab_size:150528 这个版本的chatglm,出现了这个bug
> 
> ```
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
>   File
> "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py",
> line 198, in <fused code>
>     cos, sin = F.embedding(position_id, cos.squeeze(1)).unsqueeze(2), \
>         F.embedding(position_id, sin.squeeze(1)).unsqueeze(2)
>     q, k = (q * cos) + (rotate_half(q) * sin), (k * cos) + (rotate_half(k) * sin)
>             ~~~~~~~ <--- HERE
>     return q, k
> RuntimeError: The size of tensor a (103) must match the size of tensor b (102) at
> non-singleton dimension 0
> ```

用的是main.py吗，可以先在main.py的第65行输出一下attention_mask的维度看一下是二维的还是四维的

**Comment by TianWuYuJiangHenShou** [comment]
torch.Size([12, 650]) 是二维的

**Comment by GioGioBond** [comment]
> torch.Size([12, 650]) 是二维的

我之前那个版本GLM的版本有问题，配置文件跟模型匹配有出入，导致只有我自己能用，你们都用不了，我现在在调试最新的GLM版本，如果不急的话，你可以等一下

**Comment by GioGioBond** [comment]
@TianWuYuJiangHenShou 用现在的main.py，配合现在https://huggingface.co/THUDM/chatglm-6b的模型，可以运行
